### ISSUE TITLE
Pattern Library Critique - Genevieve

### ISSUE THREAD

**Issue by nep2ne** [Sebby-T/sebastianturner.ca#1]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | Good, works very well and is unique enough | **Wow! I never would have thought that would work so well!** | 3pts
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | **The project is super effective and easy to use** | 3pts
| **Quality** | Non-existent | Acceptable quality, more work could be done | Good quality, up to the expectations of the teacher | **Stunning quality, this person rocks!** | 3pts
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | **Amazing, over-the-top amount of effort** | 3pts
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** | 3pts

Total: 15/15 pts
I confirm that I think this is an appropriate grade for the project I just reviewed.

Feedback:
-Overall amazingballs. 
- Good colour choices, good contrast between darks and bright highlights
- Cabin typeface is a revelation. I want to use it myself!
- I love that you created LOTS of icons
- The hero banner and project banners are great
- Nice animation on buttons, especially the gradient button - very creative
- Footer looks great, and the gradient soc. media icons are beautiful
- Nice underline hover on the header nav
- Projects Nav is DOPE.
- Responsiveness: fix social media nav - it's cut off at smaller sizes for some reason
- hero banner looks great at smaller size, but you may want to consider fading out the background to increase legibility.
- A fantastic effort that very effectively showcases your expertise in web design.

**Comment by Sebby-T** [comment]
Thankyou very much
