### ISSUE TITLE
Peer Review - Erica Rios

### ISSUE THREAD

**Issue by Pinestorm** [Sebby-T/sebastianturner.ca#3]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | Good, works very well and is unique enough | **Wow! I never would have thought that would work so well!** |
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | **The project is super effective and easy to use** |
| **Quality** | Non-existent | Acceptable quality, more work could be done | Good quality, up to the expectations of the teacher | **Stunning quality, this person rocks!** |
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | **Amazing, over-the-top amount of effort** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** |

I really like the look and feel of your website. The simple black and whites work very well and the accents really make certain elements pop out. As far as I could see most elements worked well in all screen sizes. The only issues I have are with the breakdown section and your card. I don't think the triangle in the section has to be so large, unless you plan on adding an image in there later. The card I assume has a placeholder image in it, however it looks too inconsistent with the rest of your patterns. Maybe style the text or border to look closer to your other patterns. Overall I think this is very well done and looks stunning!

**Comment by Sebby-T** [comment]
Thank you very much
